### ISSUE TITLE
[REFACTOR] 헥사고날 아키텍처 도입

### ISSUE THREAD

**Issue by yeong0jae** [OBJECT-INHATC/INHA_CARPOOL_SERVER#9]
## To-Do ☑️
- [ ] User 도메인 리펙토링
- [ ] History 도메인 리팩토링
- [ ] Carpool 도메인 리팩토링
- [ ] Topic 도메인 리팩토링
- [ ] scheduler 도메인 리팩토링
- [ ] Report 도메인 리팩토링
- [ ] Feedback 도메인 리팩토링
